version: '3'

volumes:
    data:

services:
  nodejs:
    image: node
    container_name: nodejs
    restart: unless-stopped
    working_dir: /home/node/app
    command: "npm start"
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo_express
      ME_CONFIG_BASICAUTH_PASSWORD: 123Mudar
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123Mudar
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123Mudar
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - mongo-compose-network


networks: 
    mongo-compose-network:
      driver: bridge