# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5959dcfc1318af62d073a66cadcd7747df2a323a023e3d789bd9b6c0f4edff665a69c4c06537d3ebd111730aae42a6f0fd32b8220f8162fb732a66d439039de2

test:
  secret_key_base: 502e3e53f871f3ce053eda2787553329a4a8fbfe4b961a04b26c3249c40480b372b667590e33dd17212f7a13c533351b3f8a5c15f41c887f5b8ef650742de4a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
