const config = {
	pageToken: 'EAAIvllNEF6UBAIId6SoXsZANYzOSNhD8pmdVggZCrhZBIGlbmleIXCq5kq4pqsqHXPUCoLqsVYzZB6i0avZAsbouCT9JXTFxJZAifvChpZACsYZBdXWQkRqYceQ3oWWDpuh8Y1sgptl18byDE9WwNeFZAEDWgH9la0Hxpt2amBKLCRwZDZD'
}
module.exports = config;