version: '3.1'

services:

  mydb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123mudar

  adminer:
    image: adminer
    restart: always
    ports:
      - 3307:8080